# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

	config.vm.define "ldap" do |ldap|
		ldap.vm.hostname = "ldap"
		ldap.vm.box = "centos-7.2-x86_64"
		ldap.vm.network "private_network", ip: "192.168.25.5"
		ldap.vm.provider "virtualbox" do |machine|
	machine.name = "ldap"
#	machine.cpus = 1
	machine.memory = 512
end
end

config.vm.provision "shell", inline: "yum install -y nano vim python-pip"
config.vm.provision "shell", inline: "pip install setuptools pexpect==3.3"
#config.vm.provision "ansible" do |ansible|
#  ansible.playbook = 'ldap/provision.yml'
#  ansible.verbose = 'vv'
#  end
end
