- name: Provision with Ansible
  hosts: all
  become: yes

  pre_tasks:
  - debug: msg="Let's do this"

  roles:
  - jenkins
  - tomcat
  - web

  vars:
   tomcat_port: 10100
   jenkins_port: 9090
   nginx_port: 8080


