---
- debug: msg="Will install mysql"
- name: mysql install
  yum: name={{item}} state=latest
  with_items:
   - mysql
   - mysql-server
   - MySQL-python
- name: init mysql
  command: /usr/bin/mysql_install_db --user=mysql
- name: starting mysql
  service: name=mysqld state=running

