# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

	config.vm.define "ldap" do |ldap|
		ldap.vm.hostname = "ldap"
		ldap.vm.box = "vagrant-centos-6.7-x86_64"
		ldap.vm.network "private_network", ip: "192.168.25.50"
		ldap.vm.provider "virtualbox" do |machine|
	machine.name = "ldap"
	machine.cpus = 1
	machine.memory = 2048
end
end

config.vm.provision "shell", inline: "yum install -y nano vim"
config.vm.provision "ansible" do |ansible|
  ansible.playbook = 'ldap/provision.yml'
  ansible.verbose = 'vv'
  end
end
